apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kantin-ingress
  annotations:
    # Penting agar routing ke /api tidak bingung
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http: # Baris 'host' dihapus agar bisa diakses via IP Public AKS
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: backend-service
            port:
              number: 5000
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend-service
            port:
              number: 80
